
version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - apt-get update -y
  pre_build:
    commands:
      - echo Inside pre build...
      - aws --version
  build:
    commands:
      - echo Build started on `date`
      - echo Building jar file...
      - mvn clean install -DskipTests
      - echo Building the Docker image...
      - docker build --build-arg BUILD_DB_USER=$DB_USER --build-arg BUILD_DB_PASSWORD=$DB_PASSWORD --build-arg BUILD_ACCESS_KEY_ID=$ACCESS_KEY_ID --build-arg BUILD_SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY -t rewygroup/backend:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo test......
      - echo Pushing the Docker images...
      - docker push rewygroup/backend:latest
      - echo Writing image definitions file...
artifacts:
  files: imagedefinitions.json
