version: '2'
services:
  frontend:
    image: rewygroup/frontend:latest
    ports:
      - '80:80'
    depends_on:
      - backend
  backend:
    image: rewygroup/backend:latest
    ports:
      - '4000:4000'